### ISSUE TITLE
Make "frozen" submodule use https:// URLs, not SSH URLs

### ISSUE THREAD

**Issue by thp-hatch** [Kronuz/constexpr-mph#1]
When recursively cloning using a machine without SSH set up, cloning fails, because the "frozen" submodule uses a SSH URL. Since it's on Github, using the https:// URL should be just as well, and allows cloning without SSH.

**Comment by thp-hatch** [comment]
IoW:
```
diff --git a/.gitmodules b/.gitmodules
index 70945cd..ab9fb27 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,3 +1,3 @@
 [submodule "frozen"]
        path = frozen
-       url = git@github.com:serge-sans-paille/frozen.git
+       url = https://github.com/serge-sans-paille/frozen.git
```

**Comment by Kronuz** [comment]
I’ve updated the submodule to use https. Thank you.
